from . import product
from . import category
from . import customer
from . import order
from . import order_item
from . import product_delivery
from . import commission
from . import commission_on_line
from . import inherited_fields
from . import stock
from . import res_config_settings
from . import res_location
from . import selected_many2one_fields